### PR TITLE
Create functionality for Friendships (v1)

### PR DESCRIPTION
**Pull request by carlos-osorio-developer**
## Add functionality for:

- Ask another user for a friendship.
- Accept or reject other users' requests for friendship.
- Display a list of pending invitations.
- Display user's posts and friends' posts.

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes required👈
**Hello @carlos-osorio-developer, I'm impressed with your hard work, let's just fix few issues before we move**

**To highlight:**

1.  Friendship model `belongs_to :user` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

2. Friendship model `belongs_to :friend, class_name: "User"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

3. User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

4. User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

5. User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

6. User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

<hr>

**Changes to make**

- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)), currently there is no button to invite friendship on users list page(all users list page).
**Fix this issue and submit another request**

**[OPTIONAL]**

- [ ] You can include a button to unfriend an existing friendship.
- [ ] You can also include a button to cancel a sent friendship request.

<hr>

Just in case you have a question about the review, reach me on slack as Elisha kyakopo.

Cheers 💪✔

**Comment by carlos-osorio-developer** [comment]
The button is there, but you have to be logged in. And you can not send a Friendship request to yourself. So you have to create more than 1 user to see the button.

It would be better if you add a screenshot of the app instead of just a screenshot of the requirement.

This is the screenshot of the button working

**Comment by elisha2kyakpo1** [comment]
I'm sorry that I have wasted your time, what makes think that I didn't create two users for me to know if a friendship request, and accepting a friendship request is done between two users, are you telling that if I pulled from remote, I'm not going to find new data about the same?

**Comment by carlos-osorio-developer** [comment]
No, I'm telling you that you should at least go to app/views/users and check the files there, is better to check the code instead of just the app from the browser, because the code has conditions. You probably sent the friendship request first from the user profile and then went to the users' list. 

If a friendship request is already sent you won't see the button again, because the request has been already sent. 

The review should be more exhausting before rejecting the PR, because, as you know, we only have 3 reviews, you are not only wasting my time, also my limited reviews.

**Comment by elisha2kyakpo1** [comment]
I would advise you to create a zoom link so that we can chat and see how best we can resolve this issue. If this project had a review limit, I would have told you, just submit another review request without changing anything, and another code reviewer will go through it and you will be told the outcome.

**Review by bini-i — APPROVED** [review]
# Status: Approved :heavy_check_mark:          
### Hello @carlos-osorio-developer  :wave: 

Your project looks good and inverse friendship is interestingly set up by querying the Friendship table using a scope.

Thanks for working on the requirements suggested by the previous reviewer.  Your project is approved :tada:  however please make sure to work on the following before proceeding to the next milestone.
- Kindly include unit and integration tests as pointed out [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png). [Optional]

#### If you have any question feel free to ask within the PR and ping me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)#

**Pull request merged**
